### ISSUE TITLE
Launching issues

### ISSUE THREAD

**Issue by DJang11** [PolarBean/DLC_ROI_tool#10]
Hi,
I am new to using open-source software, and I am not sure how to launch the application.
I have already created the environment, but I do not know what command to type in the shell.

Thank you!

Best,
DJ

**Comment by PolarBean** [comment]
python ROI_tool.py from within the activated environment and while in the DLC_ROI_tool directory :)

**Comment by DJang11** [comment]
Thank you so much! 
Lastly, is it possible to add circle regions for the future?

**Comment by PolarBean** [comment]
haha #1 requested feature. I have the code for it written up just need to test and push :) really soon
