### ISSUE TITLE
error/s when loading DLC h5 file

### ISSUE THREAD

**Issue by filos93** [PolarBean/DLC_ROI_tool#13]
Hey, sorry to bother you first of all thanks for the great tool trying to use it :) unfortunately, when I load the DLC h5 file it gives me back this error: "KeyError: "labels ['likelihood'] not found in level", if I ignore that I get this other error message: "AttributeError: 'MousePositionTracker' object has no attribute 'cropping'", finally this: "AttributeError: 'MousePositionTracker' object has no attribute 'bp_data'".

I used DLC on a single animal and tracking was perfect, I also tried with the CSV files but still getting the same errors. Can you help me, please? Thanks in advance :)

**Comment by PolarBean** [comment]
This sounds like the error you would get from using the tool on a multi-animal file.
