### ISSUE TITLE
Application Not Launching 

### ISSUE THREAD

**Issue by bholcom5** [PolarBean/DLC_ROI_tool#14]
Hi there,
I'm looking forward to using this package, but I'm having trouble opening the application. I'm still very new to programming and using packages from github, so forgive me if this issue is something simple that I'm missing. I active that environment for this package with 'conda activate _ROI_ENV'  then I try to open the application with "python -m DLC_ROI_tool". In the readme file, it just says to launch the application but doesn't provide a specific command. Hope to hear back soon, and thanks in advance. 
Best, Blake

**Comment by PolarBean** [comment]
Assuming youre in the cloned directory “python DLC_ROI_tool.py” would be the correct command. I wrote this package a while ago and agree that the instructions should be more clear. 

Let me know how you go 😊

**Comment by bholcom5** [comment]
“python DLC_ROI_tool.py”  did not work, but "python ROI_tool.py" seems to
have worked. Going through the workflow now. Thanks for the help!

**Comment by PolarBean** [comment]
Haha woops, my bad! Ok glad its working now :)
