### ISSUE TITLE
Launching GUI

### ISSUE THREAD

**Issue by natalier11** [PolarBean/DLC_ROI_tool#15]
Hi!
I'm pretty new to python and DLC as a whole. I was just wondering what command I should be using to launch the ROI_ENV GUI. I have the environment installed via the .yml file but am not sure how to get the actual GUI itself to open. Thanks in advance!

**Comment by PolarBean** [comment]
make sure you're in the cloned directory
`cd DLC_ROI_tool`
then run
`python ROI_tool.py `
let me know how you go :)

**Comment by natalier11** [comment]
I'm having one more issue, it's saying there is no cv2 module to import from the ROI_tool.py file. I ran
`conda env create -f ROI_ENV.yml`
in it's entirety so I'm not sure what I'm missing. Let me know if you have any idea how to fix this, thanks!
![DLC ROI import cv2 error](https://user-images.githubusercontent.com/73397911/103973476-1e653d80-5135-11eb-85c4-8b6636beb32b.png)

**Comment by PolarBean** [comment]
you need to activate the conda environment after installing. (notice on the left it says your current environment is the base (default) env. 
`conda activate ROI_ENV`   should do the trick!

**Comment by natalier11** [comment]
Thank you so much, I appreciate your help! It works!

**Comment by PolarBean** [comment]
great :)
