### ISSUE TITLE
bucket length

### ISSUE THREAD

**Issue by aXcELLcore** [PolarBean/DLC_ROI_tool#16]
Hi, I tried to use the DLC_ROI but i get this error after i set the bucket length (also i dont know what it is) , can u help me please
![image](https://user-images.githubusercontent.com/56560672/145488230-a1254854-e8ab-4531-82ec-98d09e4873e5.png)

**Comment by PolarBean** [comment]
Binning tells you how long the animal spent in each ROI per bin seconds, so if you put in 30 seconds it would give you roi time per 30 seconds. The issue you are facing is from using pandas 1.x, which I have just replicated. 
in the installation instructions we note to use pandas 0.25.3, this can be installed with `pip install pandas==0.25.3`. This solved this error message for me, so I will close this issue for now, if you run into the error again feel free to reopen. 

all the best and happy ROI-ing!
