### ISSUE TITLE
Bucket length

### ISSUE THREAD

**Issue by apassagelee** [PolarBean/DLC_ROI_tool#18]
A simple question, really. What is the bucket length and how should I choose it?

**Comment by PolarBean** [comment]
its either how many seconds or how many frames per time bin for your summary statistics (i'll check when back at work) :)

**Comment by Destiny-123** [comment]
Hi I have the same question about how we choose bucket length.

**Comment by linhtruong-ns** [comment]
Hi, I have the same issues with choosing the Bucket length. It would be great if you could give more detail. Thx

**Comment by PolarBean** [comment]
the roi tool outputs a summary of your input data. So for each bucket of time how many seconds did the animal spend in each specified region. You can split this into one minute buckets by specifying bucket length as 60
