### ISSUE TITLE
Difficulty Loading DeepLabCut file

### ISSUE THREAD

**Issue by jacobk14** [PolarBean/DLC_ROI_tool#3]
Hi, 
I was successfully able to open the guy, draw, and name the ROI's, and save them to a file; however, when I clicked on the Load Deeplabcut File button, nothing happened. I have included the message the populated in console in the image below. It begins at "Exception in Tkinter Callback". Do you have any suggestions on how to fix this?
![image](https://user-images.githubusercontent.com/66270143/85632347-27813800-b645-11ea-8d5e-05b9d59335a5.png)

**Comment by PolarBean** [comment]
it looks like you have a different version of tkinter installed. did you install the environment from the provided yml file?

**Comment by jacobk14** [comment]
I tried installing the env using conda env create -f as well as updating a current environment using conda env update -f. Both resulted in a message saying ResolvePackageNotFound: with a list of packages underneath.

**Comment by PolarBean** [comment]
Try
`conda update --all’

Then build the environment again.

And if that doesn’t work Post the full trace back and I’ll fix it for you.

**Comment by jacobk14** [comment]
I am still getting the same error message (picture below). Also, here is the traceback I get when click on "Load Deeplabcut File" in the guy. 
![image](https://user-images.githubusercontent.com/66270143/85664789-a77cc180-b688-11ea-8869-7033622c4f06.png)
![image](https://user-images.githubusercontent.com/66270143/85665005-ead73000-b688-11ea-9e28-97c257ad49ac.png)

**Comment by PolarBean** [comment]
Conda is frustrating at times. Install tkinter math PIL pandas==0.25.3 numpy openCV and tables manually into your env

**Comment by jacobk14** [comment]
I manually installed the packages; however, I am still getting the same error. It seems like tkinter is the issue since the traceback says "exception in tkinter callback", but when I tried to install tkinter (using sudo apt-get install python3-tk), it said python3-tk is already the newest version.

**Comment by PolarBean** [comment]
Or conda install -c anaconda tk

**Comment by PolarBean** [comment]
Try running it from the terminal after you’ve activated your conda environment

**Comment by jacobk14** [comment]
I was able to open the gui from the terminal but got the same error message when I tried to click the load deeplabcut file button.

**Comment by PolarBean** [comment]
Ive fixed some code to increase compatibility with linux. clone the repo again and it will work :)

**Comment by jacobk14** [comment]
Thank you so much for taking the time to do that. I was able to get it to work! I put my final output below. What units are the time spent output values in because my video is only 5 minutes long, so they are too big to be in seconds? Also, does this GUI work for multi animal projects too or just single animal projects? Again, Thank you for answering all my questions. 
![image](https://user-images.githubusercontent.com/66270143/85765259-f0ae2f00-b6e3-11ea-9e6b-b893da2745d7.png)

**Comment by PolarBean** [comment]
its currently in frames to maximize accuracy. I can see how this would be confusing, Ill change it to seconds in an update later today :)

**Comment by PolarBean** [comment]
and the GUI has never been tested on multi-animal projects. ill look into that in the future.

**Comment by PolarBean** [comment]
Hey @jacobk14,  I've closed this issue and just want to see how you have gone with our tool?
