### ISSUE TITLE
no "detect entries and time spent" analysis

### ISSUE THREAD

**Issue by filos93** [PolarBean/DLC_ROI_tool#6]
Hey,

thanks for the ROI tool, trying to use it :) I'm not able to generate a "detect entries and time spent" analysis, I get the following errors (3) in my IDE:

-ValueError: Wrong number of items passed 13, placement implies 2
-ValueError: Shape of passed values is (1905, 13), indices imply (1905, 2)
-AttributeError: 'MousePositionTracker' object has no attribute 'bp_data'

Besides, I am not sure of the csv created after the "bodypart to ROI" step ("near" and "out" are the ROIs I've drawn). Here's the output:

,BRX,BRY,FPS,ROI,TLX,TLY
0,1244.175,1056.857142857143,30.0,near,1056.375,30.85714285714286
0,1040.7250000000001,1041.4285714285716,30.0,out,27.3875,36.0
0,1207.0062500000001,730.2857142857143,30.0,near,1011.38125,290.5714285714286
0,886.18125,828.0000000000001,30.0,out,363.8625,293.14285714285717

Can you help me? Thanks in advance!!

**Comment by PolarBean** [comment]
thanks for using the tool! did you create the environment from the ROI_ENV.yml file? this should be in the readme so i'll add it in now :)

**Comment by filos93** [comment]
Hey, thanks for your reply. I created the env from the ROI_ENV.yml file. Everything looks fine, the GUI is on and I can follow all the steps in the readme file, but still cannot get the "detect entries and time spent" analysis. Should I try something else? Am I forgetting something? Thanks again 👍

**Comment by filos93** [comment]
Also in the GUI it keeps telling me "no pickle file was found for {}, this means if you cropped your video in dlc our program will not be accurate", but I'm sure I opened the pickle file. Don't know if the real issue is here?! Thanks :)

**Comment by PolarBean** [comment]
ahhh ok thats the problem, you need to open the h5 file and the pickle file will open automatically

**Comment by PolarBean** [comment]
Try this and let me know if it helps

**Comment by PolarBean** [comment]
also are you using single or multi-animal?

**Comment by filos93** [comment]
thanks for reply, I'm using multi-animal. Is that a problem?

**Comment by PolarBean** [comment]
ohh, sorry this tool  is only compatible with single animal at the moment. Ill add in multi-animal functionality in a couple of weeks. Ill add this to the readme

**Comment by PolarBean** [comment]
moved discussion here :) https://github.com/PolarBean/DLC_ROI_tool/issues/7

**Comment by filos93** [comment]
thank you so much for your replies, I'll wait for it :)

**Comment by PolarBean** [comment]
Simba might have support if you need to analyse urgently https://github.com/sgoldenlab/simba
